# Preface {.unnumbered}

This is an informal attempt at analyzing something "in public". Not that I expect anybody will be watching.

The background for the project is rooted in an merging interest in the topic "Values in Social Work Research". This interest probably stems from having worked a few years at an institution, which main activity is teaching and researching Social Work (although I'm not sure this order reflects the activities priority). It should also probably be noted that the content in no way reflects the institution's views on matters discussed. This is "private me" doing exercises.

Although the topic of "Social Work Values" is sometimes raised, even in highly temperatured debates on what Social Work as a Research Field should be doing - and not be doing, on the one hand, and Social Work Values is defined for and known to practitioners (including me), on the other, I'm not really sure what we are talking about when we refer to values of Social Work Research (as opposed to Practice). That's kind of embarrassing - after all I'm currently paid to be doing Social Work Research (although that may change - there's statistically slim chances of further employment in higher education).

Also, I need to think through some of these issues before deciding how to move forward in some concrete analysis I've been postponing...

Although I strongly believe researchers should keep out of the blogosphere, on the one hand, and feeling almost certain that I will display some embarrassing holes in knowledge and skills, even related to core topics in Social Work and Social Science, I've decided to do some explorations out in the open.

Partly, I believe this can be justified through "values", referring to what's socially "good", should imply values is discussed publicly. At least as far as possible. "Research values" implies community. And even though the community probably ain't listening, this book is open for comments, corrections, contributions etc.

Also I just love how the RStudio - Quarto - Git - GitHub - GitHub Pages workflow makes literate programming extremely fun...
